# Generated by Django 5.2.7 on 2025-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_dimdate_dimeventtype_dimgender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimdate',
            old_name='week',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='dimdate',
            name='date_name',
        ),
        migrations.AddField(
            model_name='dimdate',
            name='day_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dimdate',
            name='is_weekend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dimdate',
            name='month_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
