# Generated by Django 5.2.7 on 2025-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimdistrict',
            name='code',
            field=models.CharField(blank=True, help_text='Short immutable district code for Bibs (e.g. LKO). Fill via admin/backfill.', max_length=10, null=True),
        ),
    ]
