# Generated by Django 5.2.7 on 2026-07-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0005_dimdistrict_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('tournament_start', models.DateTimeField()),
                ('tournament_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='app_admin.dimeventtype')),
            ],
            options={
                'ordering': ['tournament_start'],
            },
        ),
    ]
