# Generated by Django 5.2.7 on 2026-07-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_dimdistrict_code'),
        ('app_tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('minimum_players', models.PositiveSmallIntegerField(default=1)),
                ('maximum_players', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_entries', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_categories', to='app_admin.dimeventcategory')),
                ('entry_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_categories', to='app_tournaments.entryformat')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'category'), name='unique_category_per_tournament')],
            },
        ),
    ]
