# Generated by Django 5.2.7 on 2026-07-24 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0002_entryformat_tournamentcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Entry statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('seed', models.PositiveIntegerField(blank=True, help_text='Optional tournament seed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='app_tournaments.entrystatus')),
                ('tournament_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app_tournaments.tournamentcategory')),
            ],
            options={
                'ordering': ['tournament_category', 'seed', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Player order inside the entry: 1, 2, 3, etc.')),
                ('is_captain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app_tournaments.tournamententry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_entry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entry', 'position'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'player'), name='unique_player_per_tournament_entry'), models.UniqueConstraint(fields=('entry', 'position'), name='unique_player_position_per_entry')],
            },
        ),
    ]
