# Generated by Django 5.2.7 on 2026-07-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0003_entrystatus_tournamententry_tournamententryplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tournamentcategory',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tournamentcategory',
            name='unique_category_per_tournament',
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='tournament_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_categories', to='app_tournaments.tournamentformat'),
        ),
    ]
