# Generated by Django 5.2.7 on 2026-07-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0004_tournamentformat_alter_tournamentcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Match statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Group Stage, Quarterfinal, Semifinal, Final', max_length=100)),
                ('round_number', models.PositiveIntegerField(help_text='Controls the order in which rounds are played.')),
                ('is_knockout', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='app_tournaments.tournamentcategory')),
            ],
            options={
                'ordering': ['tournament_category', 'round_number'],
                'constraints': [models.UniqueConstraint(fields=('tournament_category', 'round_number'), name='unique_round_number_per_category'), models.UniqueConstraint(fields=('tournament_category', 'name'), name='unique_round_name_per_category')],
            },
        ),
    ]
