# Generated by Django 5.2.7 on 2026-07-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0005_matchstatus_tournamentround'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(help_text='Match order within this round.')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_entry_one', to='app_tournaments.tournamententry')),
                ('entry_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_entry_two', to='app_tournaments.tournamententry')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='app_tournaments.matchstatus')),
                ('tournament_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_tournaments.tournamentround')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='app_tournaments.tournamententry')),
            ],
            options={
                'ordering': ['tournament_round', 'match_number'],
                'constraints': [models.UniqueConstraint(fields=('tournament_round', 'match_number'), name='unique_match_number_per_round')],
            },
        ),
    ]
