# Generated by Django 5.2.7 on 2026-07-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Court 1, Court 2, Conference Hall Court', max_length=100)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='app_tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='app_tournaments.court'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_court_name_per_tournament'),
        ),
    ]
