# Generated by Django 5.2.7 on 2026-07-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0007_match_scheduled_end_court_match_court_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('best_of_sets', models.PositiveSmallIntegerField(help_text='Example: 3 means best of 3 sets.')),
                ('points_to_win_set', models.PositiveSmallIntegerField(help_text='Example: 21 for badminton.')),
                ('winning_margin', models.PositiveSmallIntegerField(default=2)),
                ('maximum_points', models.PositiveSmallIntegerField(blank=True, help_text='Optional score cap, such as 30 in badminton.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='scoring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_categories', to='app_tournaments.scoringrule'),
        ),
    ]
