# Generated by Django 5.2.7 on 2026-07-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0008_scoringrule_tournamentcategory_scoring_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('entry_one_score', models.PositiveIntegerField(default=0)),
                ('entry_two_score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='app_tournaments.match')),
                ('winner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets_won', to='app_tournaments.tournamententry')),
            ],
            options={
                'ordering': ['match', 'set_number'],
                'constraints': [models.UniqueConstraint(fields=('match', 'set_number'), name='unique_set_number_per_match')],
            },
        ),
    ]
