# Generated by Django 5.2.7 on 2026-07-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_registration_registration_type'),
        ('app_tournaments', '0009_matchset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamententry',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='The public Registration submission that created this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to='accounts.registration'),
        ),
    ]
