# Generated by Django 5.2.7 on 2026-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0010_tournamententry_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(blank=True, choices=[('top', 'Top Half'), ('bottom', 'Bottom Half')], help_text='Bracket half used only for fixture display styling.', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_slot',
            field=models.PositiveIntegerField(blank=True, help_text='Position of this match inside the tournament bracket.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='fixtures_generated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
