# Generated by Django 5.2.7 on 2026-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0011_match_bracket_side_match_bracket_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='fixture_type',
            field=models.CharField(choices=[('knockout', 'Knockout'), ('round_robin', 'Round Robin')], default='knockout', help_text='Choose how confirmed entries will be paired when fixtures are generated.', max_length=20),
        ),
    ]
