# Generated by Django 5.2.7 on 2026-09-14 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tournaments', '0016_tournament_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text="Public identifier used in this tournament's shareable registration link."),
        ),
    ]
