# Generated by Django 5.2.7 on 2025-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_id', models.PositiveIntegerField()),
                ('lap_time', models.DurationField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Time entry',
                'verbose_name_plural': 'Time entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
