# Generated by Django 5.2.7 on 2026-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='bib_id',
            field=models.CharField(max_length=50),
        ),
    ]
