# Generated by Django 5.2.7 on 2026-04-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_registration_reg_mobile_idx_and_more'),
        ('app_races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceregistration',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_entries', to='accounts.registration'),
        ),
    ]
