# Generated by Django 5.2.7 on 2026-04-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_races', '0002_raceregistration_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Heat 1, Elite Group, Wave A', max_length=100)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='app_races.race')),
            ],
            options={
                'ordering': ['actual_start_time', 'name'],
            },
        ),
    ]
