# Generated by Django 5.2.7 on 2026-04-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_registration_heat_registration_heat_number_and_more'),
        ('app_races', '0003_heat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heat',
        ),
    ]
