# Generated by Django 5.2.7 on 2026-04-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_registration_heat_registration_heat_number_and_more'),
        ('app_races', '0004_delete_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceregistration',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='race_entries', to='accounts.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raceregistration',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_registrations', to='app_races.race'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app_races.race')),
            ],
        ),
        migrations.AddField(
            model_name='raceregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='app_races.event'),
        ),
        migrations.AlterUniqueTogether(
            name='raceregistration',
            unique_together={('participant', 'event')},
        ),
    ]
