# Generated by Django 5.2.7 on 2026-07-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_registration_profession_and_more'),
        ('app_races', '0006_event_description_event_distance_km_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_races.event')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_entries_as_player_one', to='accounts.registration')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_entries_as_player_two', to='accounts.registration')),
            ],
        ),
    ]
