# Generated by Django 5.2.7 on 2026-07-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_dimdistrict_code'),
        ('app_races', '0007_doublesentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='race_events', to='app_admin.dimeventcategory'),
        ),
    ]
