# Generated by Django 5.2.7 on 2026-07-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_races', '0008_event_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoublesEntry',
        ),
    ]
