# Generated by Django 5.2.7 on 2026-09-14 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_races', '0012_event_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text="Public identifier used in this race's shareable registration links.", null=True),
        ),
    ]
