# Generated by Django 5.2.7 on 2025-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('business', 'Business')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('representing_from', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('events', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
