# Generated by Django 5.2.7 on 2025-11-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app_admin', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='registration',
            name='district_fk',
            field=models.ForeignKey(blank=True, help_text='Selected district (FK to DimDistrict).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_fk', to='app_admin.dimdistrict'),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Selected state (FK to DimState).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='app_admin.dimstate'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district',
            field=models.CharField(blank=True, help_text='Legacy/free-text district field; used for migration.', max_length=200),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='events',
        ),
        migrations.AddField(
            model_name='registration',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events the registrant is participating in.', related_name='registrations', to='app_admin.event'),
        ),
    ]
