# Generated by Django 5.2.7 on 2025-11-06 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_registration_options_registration_district_fk_and_more'),
        ('app_admin', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12 digit Aadhaar number without spaces.', max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='Aadhaar'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district',
            field=models.CharField(blank=True, help_text='Legacy/free-text district field; used for migration.', max_length=200, verbose_name='District (legacy)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district_fk',
            field=models.ForeignKey(blank=True, help_text='Selected district (FK to DimDistrict).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_fk', to='app_admin.dimdistrict', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events the registrant is participating in.', related_name='registrations', to='app_admin.event', verbose_name='Events'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Father's name"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Include country code if applicable, e.g. +91XXXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')], verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profession',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('business', 'Business')], max_length=20, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='representing_from',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representing from'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Selected state (FK to DimState).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='app_admin.dimstate', verbose_name='State'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['mobile_number'], name='reg_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['aadhar_number'], name='reg_aadhar_idx'),
        ),
    ]
