# Generated by Django 5.2.7 on 2025-11-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registration_options_and_more'),
        ('app_admin', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events the registrant is participating in.', related_name='registrations', to='app_admin.dimeventcategory', verbose_name='Events'),
        ),
    ]
