# Generated by Django 5.2.7 on 2025-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_registration_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.CharField(blank=True, help_text='Computed competition category for registrant (auto-calculated).', max_length=255, null=True, verbose_name='Assigned category'),
        ),
    ]
