# Generated by Django 5.2.7 on 2025-11-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registration_gender'),
        ('app_admin', '0005_dimdistrict_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bib_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Bib ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='bib_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistrationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('age_category', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.dimdistrict')),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'year', 'age_category', 'gender'], name='seq_idx')],
                'unique_together': {('district', 'year', 'age_category', 'gender')},
            },
        ),
    ]
