# Generated by Django 5.2.7 on 2025-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_registration_bib_id_registration_bib_released_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
