# Generated by Django 5.2.7 on 2026-04-09 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_full_name_profile_bio'),
        ('app_admin', '0005_dimdistrict_code'),
        ('app_races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='district',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='events',
        ),
        migrations.AddField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(blank=True, help_text='The specific race event the user is registering for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_registrations', to='app_races.race', verbose_name='Selected Race'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='Aadhaar'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned category'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_fk', to='app_admin.dimdistrict', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')], verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='app_admin.dimstate', verbose_name='State'),
        ),
    ]
