# Generated by Django 5.2.7 on 2026-04-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_registration_district_and_more'),
        ('app_admin', '0005_dimdistrict_code'),
        ('app_races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registration',
            name='reg_mobile_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='reg_aadhar_idx',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Registration ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Aadhaar'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_fk', to='app_admin.dimdistrict'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_registrations', to='app_races.race', verbose_name='Selected Race'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='app_admin.dimstate'),
        ),
    ]
