# Generated by Django 5.2.7 on 2026-04-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_registration_reg_mobile_idx_and_more'),
        ('app_races', '0003_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='heat',
            field=models.ForeignKey(blank=True, help_text='The specific starting group/wave for this athlete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='app_races.heat', verbose_name='Assigned Heat'),
        ),
    ]
