# Generated by Django 5.2.7 on 2026-04-16 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_registration_heat'),
        ('app_admin', '0005_dimdistrict_code'),
        ('app_races', '0003_heat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='heat',
        ),
        migrations.AddField(
            model_name='registration',
            name='heat_number',
            field=models.IntegerField(blank=True, help_text='The group/wave number assigned based on DOB.', null=True, verbose_name='Heat Number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='Aadhaar'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')], verbose_name='Mobile number'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['mobile_number'], name='reg_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['aadhar_number'], name='reg_aadhar_idx'),
        ),
    ]
