# Generated by Django 5.2.7 on 2026-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_registration_heat_registration_heat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profession',
        ),
        migrations.AddField(
            model_name='registration',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='School / College / Club'),
        ),
    ]
