# Generated by Django 5.2.7 on 2026-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_registration_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('race', 'Race'), ('tournament', 'Tournament')], default='race', max_length=20, verbose_name='Registration type'),
        ),
    ]
